"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, UserRound } from "lucide-react";
import Link from "next/link";
import { AuthStepper } from "./auth-shell";

export function RegisterForm() {
  const [values, setValues] = useState({ name: "", email: "", password: "", confirm: "" });
  const [show, setShow] = useState(false); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false);
  const update = (key: keyof typeof values, value: string) => { setValues({ ...values, [key]: value }); setError(""); };
  const strong = values.password.length >= 8 && /[A-Z]/.test(values.password) && /\d/.test(values.password);
  function submit(event: FormEvent) { event.preventDefault(); if (!values.name || !values.email || !strong || values.password !== values.confirm) { setError(values.password !== values.confirm ? "Passwords do not match." : "Please complete all required fields."); return; } setSubmitted(true); }
  if (submitted) return <div className="success-view"><div className="success-icon"><Check size={34} /></div><p className="eyebrow">Check your inbox</p><h1>Verify your email</h1><p className="subcopy">We sent a verification link to <strong>{values.email}</strong>. Open it to finish creating your account.</p><Link className="primary-button" href="/login">Continue to sign in <ArrowRight size={17} /></Link></div>;
  return <><AuthStepper active={1} /><div className="step-content"><div className="heading-block"><div className="heading-icon"><UserRound size={20} /></div><p className="eyebrow">Create your account</p><h1>Let’s get started</h1><p className="subcopy">Set up your admin account to manage your appointments with ease.</p></div><form onSubmit={submit} className="auth-form"><div className="form-grid"><div className="field full"><label className="field-label" htmlFor="name">Full name</label><input id="name" value={values.name} onChange={e => update("name", e.target.value)} placeholder="Alex Morgan" autoComplete="name" /></div><div className="field full"><label className="field-label" htmlFor="email">Email address</label><div className="input-with-icon"><Mail size={17} /><input id="email" type="email" value={values.email} onChange={e => update("email", e.target.value)} placeholder="alex@company.com" autoComplete="email" /></div></div><div className="field"><label className="field-label" htmlFor="password">Password</label><div className="input-with-icon trailing"><LockKeyhole size={17} /><input id="password" type={show ? "text" : "password"} value={values.password} onChange={e => update("password", e.target.value)} placeholder="Create a password" /><button type="button" className="icon-button" aria-label="Toggle password visibility" onClick={() => setShow(!show)}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div><div className="field"><label className="field-label" htmlFor="confirm">Confirm password</label><div className="input-with-icon"><LockKeyhole size={17} /><input id="confirm" type="password" value={values.confirm} onChange={e => update("confirm", e.target.value)} placeholder="Repeat password" /></div></div></div>{values.password && <div className="password-check"><span className={values.password.length >= 8 ? "valid" : ""}><Check size={13} /> 8+ characters</span><span className={strong ? "valid" : ""}><Check size={13} /> 1 uppercase &amp; number</span></div>}{error && <p className="error-message" role="alert">{error}</p>}<button className="primary-button" type="submit">Create account <ArrowRight size={17} /></button></form><p className="terms">Already have an account? <Link href="/login">Sign in</Link></p></div></>;
}
